apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: regatas
  labels:
    app: ingest-service
spec:
  type: ClusterIP
  selector:
    app: ingest-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
